- README.md
Fix chart installation examples:
- create observe namespace automatically if it doesn't exist
- fix typo in `traces`
- fix quoting to force customer IDs and tokens to be interpreted as strings
- fix chart paths
> doc: fix installation instructions

- charts/traces/values.yaml
OpenTelemetry docs specify that environment variables should be referenced as `${env:VAR_NAME}` in the collector configuration, but in practice this does not appear to work in our configmap. Testing verifies that `${VAR_NAME}` works as expected.
> fix(traces): fix broken var references in configmap

- .github/workflows/release.yml
- Makefile
- charts/stack/Chart.lock
- examples/stack/values-l.yaml
- examples/stack/values-m.yaml
- examples/stack/values-xl.yaml
- examples/stack/values-xs.yaml
The stack example files did not correctly set grafana-agent values. Fix by namespacing them correctly.
This change also updates the stack chart lock file, which was not correctly updated in the previous change. The command used to accomplish this was also added to the Makefile.
> Fix metrics examples

- README.md
- charts/internal/endpoint/Chart.yaml
- charts/internal/endpoint/templates/_address.tpl
- charts/internal/endpoint/values.yaml
- charts/internal/events/Chart.lock
- charts/internal/events/Chart.yaml
- charts/internal/events/templates/deployment.yaml
- charts/internal/events/values.yaml
- charts/internal/logs/Chart.lock
- charts/internal/logs/Chart.yaml
- charts/internal/logs/values.yaml
- charts/internal/metrics/Chart.lock
- charts/internal/metrics/Chart.yaml
- charts/internal/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/values.yaml
- charts/traces/Chart.yaml
- charts/traces/values.yaml
Rather than generating collector URLs using a provided scheme, customer, host, and port, also allow the entire ~~address~~ endpoint (minus the URL path, which changes per agent) to be provided as a single value. If this value is provided, it overrides the others. This change also adds enforcement that if the full address is not provided, then the customer ID must be provided or the template generation will fail with a descriptive error.
This is required for (still WIP) acceptance tests, which configure the agents to use a local collector whose hostname does not follow the usual pattern (customerID.collect.observeinc.com).
> feat: use observe endpoint to auto-configure scheme/host/port/customerID 

- charts/internal/endpoint/Chart.yaml
- charts/internal/endpoint/templates/_address.tpl
- charts/internal/endpoint/values.yaml
- charts/internal/events/Chart.yaml
- charts/internal/logs/Chart.yaml
- charts/internal/metrics/Chart.yaml
- charts/stack/Chart.yaml
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/values.yaml
We disable the hostPorts by default, so without a service the pods are not reachable for writing traces. 
Setting service to "enabled" for daemonsets was not supported in our current otel-collector chart version, so this also means bumping the otel-collector chart version to the latest.
This change also fixes several edge cases in the endpoint internal chart, where incorrect endpoints were generated if collectionEndpoint was not provided.
> fix(traces): enable service by default for daemonset

- charts/internal/endpoint/Chart.yaml
- charts/internal/endpoint/templates/_address.tpl
- charts/internal/events/Chart.lock
- charts/internal/events/Chart.yaml
- charts/internal/logs/Chart.lock
- charts/internal/logs/Chart.yaml
- charts/internal/metrics/Chart.lock
- charts/internal/metrics/Chart.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
OB-20505 describes an issue wherein requests with duplicate slashes in the URL, such as `https://130594569014.collect.observeinc.com//v1/prometheus`, result in an error "Method GET is not allowed", despite the method actually being POST. While this appears to be a bug in the collector, we can also mitigate the issue here by ensuring that all generated URLs have redundant `/`s stripped.
> fix: remove trailing slash from base collection endpoint

- charts/internal/endpoint/Chart.yaml
- charts/internal/endpoint/templates/_address.tpl
- charts/internal/events/Chart.lock
- charts/internal/events/Chart.yaml
- charts/internal/logs/Chart.lock
- charts/internal/logs/Chart.yaml
- charts/internal/metrics/Chart.lock
- charts/internal/metrics/Chart.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
This type of comment is not safe to use in the context of these template functions. It can be included in generated endpoints and cause invalid config.
Fixes OB-20629
Fixes #23
> fix(all): prevent comment from being incorrectly rendered in endpoint

- charts/internal/metrics/values.yaml
- examples/stack/values-xl.yaml
Chart renders with an empty value without this.
Further in the values, the configmap passed to grafana references a `Values.prom_config.host_filter` which is never initialized.
In our environment this was resulting in memory spikes for the grafana agent that cause an OOM crash loop. Adding this value in as a default appears to stop this, and brings things in line with the previously-used kustomize definition.
> Add `host_filter: "true"` to default metrics values. 

- README.md
`stack/xl` resembles a chart name which can be confusing.
> docs: update example values links to not look like chart names

- charts/metrics/Chart.yaml
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
This PR to add clusterUid to prometheus remote_rewrite to include the tags for the prometheus metadata that is pushed to by grafana-agent.
Tested this change in eng environment - https://101.observe-eng.com/workspace/41000011/dataset/event/Observation-41046423?filter-OBSERVATION_KIND=prom_md&s=3380-1hn05klz
Related JIRA - https://observe.atlassian.net/browse/CON-1717 & https://observe.atlassian.net/browse/OB-21039
> fix: add clusteruid to remote_rewrite

- charts/metrics/values.yaml
Include all memory, cpu, fs, and network metrics by default.
> adjust cadvisor metrics scraped by default

- charts/metrics/Chart.yaml
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
Clean up the configuration section to make it a lot easier to visually parse.
Add some simple instructions around how to use the various regexes.
Fixes OB-21872
> docs: improve documentation of values used for metrics filtering

- charts/stack/templates/tests/test-stack.yaml
- charts/traces/templates/tests/test-traces.yaml
- test/cmd/client/main.go
- test/test.sh
Each kubernetes manifest is treated as a standalone test by helm, so creating configmaps to configure test pods does not work as expected -- configmaps either persist, which is a bug, or they are cleaned up before the job relying on them can be run. Avoid them entirely for the configuration of test pods.
Closes #32
> fix: remove configmaps from tests

- charts/metrics/Chart.yaml
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
This change adds support for enabling the statsd_exporter integration in grafana-agent. When enabled, statsd producers can send metrics to the service created by the metrics chart, and these will be published to observe via prometheus remote_write.
A followup will add a README to the metrics chart directory, documenting this feature among others.
> feat(metrics): add support for statsd_exporter

- .github/workflows/pre-commit.yml
Resolving the following issue
```
0s
Run make validate-chart-version
fatal: ambiguous argument 'origin/main...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- **[<file>...]'
```
> chore(ci): need fetch depth of zero

- charts/endpoint/Chart.yaml
- charts/endpoint/README.md
- charts/events/Chart.lock
- charts/events/Chart.yaml
- charts/events/README.md
- charts/events/templates/deployment.yaml
- charts/events/templates/rbac.yaml
- charts/events/templates/serviceaccount.yaml
- charts/events/values.yaml
- charts/logs/Chart.lock
- charts/logs/Chart.yaml
- charts/logs/README.md
- charts/metrics/Chart.lock
- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/proxy/Chart.yaml
- charts/proxy/README.md
- charts/proxy/templates/deployment.yaml
- charts/proxy/templates/hpa.yaml
- charts/proxy/templates/ingress.yaml
- charts/proxy/templates/service.yaml
- charts/proxy/templates/serviceaccount.yaml
- charts/proxy/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/README.md
by changing values.yaml to
```
customLabels:
environment: production
team: my-team
```
The resulting diff in the manifest is
```
11a12,13
>     environment: production
>     team: my-team
22a25,26
>     environment: production
>     team: my-team
43a48,49
>     environment: production
>     team: my-team
```
or in context:
```
apiVersion: v1
kind: ServiceAccount
metadata:
name: v0-proxy
labels:
helm.sh/chart: proxy-0.1.0
app.kubernetes.io/name: proxy
app.kubernetes.io/instance: v0
app.kubernetes.io/managed-by: Helm
environment: production
team: my-team
.....
---
apiVersion: v1
kind: Service
metadata:
name: v0-proxy
labels:
helm.sh/chart: proxy-0.1.0
app.kubernetes.io/name: proxy
app.kubernetes.io/instance: v0
app.kubernetes.io/managed-by: Helm
environment: production
team: my-team
spec: …
```
> feat(labels): add custom label capability

- updatecli/external/grafana.yml
regex needed to be tweaked to match grafana-agent-x.y.z and not include grafana-agent-operator-x.y.z
> fix: adjust the updatecli grafana-agent regex

- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.yaml
- charts/traces/README.md
- charts/traces/ci/test-values.yaml
- charts/traces/values.yaml
We need to explicitely set opentelemetry-collector.fullnameOverride to observe-traces to match our documentation. The issue is by default the `helm install` uses the release name to build the service name so
`helm install blah` results in
```
apiVersion: v1
kind: Service
metadata:
name: blah-traces
namespace: observe
```
Going forward `helm install blah` will always result in
```
apiVersion: v1
kind: Service
metadata:
name: observe-traces
namespace: observe
```
> fix: define opentelemetry-collector.fullnameOverride so observe-traces fixed as the service name

- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/README.md
- charts/traces/values.yaml
k8sattributes processor now natively supports extracting `k8s.cluster.uid`, so we don't need to handle this through the resource processor anymore.
Kustomize PR: https://github.com/observeinc/manifests/pull/131
> fix(traces): extract k8s.cluster.uid through k8sattributes

- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/README.md
- charts/traces/values.yaml
traces:
- `connection` pod_association needs to be a separate rule
- filtering nodes for caching pod attributes tends to break metrics and require nodes RBAC, which is not well documented upstream, so reverting for now
Kustomize PR: https://github.com/observeinc/manifests/pull/132
> fix(traces): split pod_association rules and remove node filtering in k8sattributes processor

- charts/logs/Chart.lock
- charts/logs/Chart.yaml
- charts/logs/README.md
- charts/logs/values.yaml
- charts/metrics/Chart.lock
- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/README.md
Our kustomize manifests pull images from dockerhub which has higher rate limits than fluent-bit's registry.  This ensures that our kustomize and helm deployments are in sync.
> fix: pull fluent-bit image from docker hub

- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
https://www.notion.so/observeinc/Kubernetes-Follow-up-on-OB-27594-0c3e01f24f554505bde424517870bdbb#1c00281607504f19ada61a3a75565411
Address #2 
Tested and verified in K8s that metrics are dropped
> fix(metrics): drop pod metrics by default

- README.md
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.yaml
- charts/traces/README.md
- charts/traces/values.yaml
https://observe.atlassian.net/browse/OB-28334
Introduces a new optional configuration value `global.observe.otelPath` which is set to `/v1/otel` by default. Can be set to `/v2/otel` to send OpenTelemetry observations to v2 version of collection endpoint.
> fix(traces): Makes collection endpoint path configurable

- charts/endpoint/Chart.yaml
- charts/endpoint/README.md
- charts/events/Chart.lock
- charts/events/Chart.yaml
- charts/events/README.md
- charts/logs/Chart.lock
- charts/logs/Chart.yaml
- charts/logs/README.md
- charts/metrics/Chart.lock
- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/metrics/values.yaml
- charts/proxy/Chart.yaml
- charts/proxy/README.md
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.lock
- charts/traces/Chart.yaml
- charts/traces/README.md
The grafana-agent helm chart deploys CRDs by default
```
crds:
create: true
```
https://github.com/grafana/agent/blob/9d65d9f483ea2690f34681431dd32b6356a6026f/operations/helm/charts/grafana-agent/values.yaml#L23
Which tends to cause unnecessary errors for our customers, such as:
```
Failed sync attempt to 438b29f3078f29e227ed9569cb40b065172af04c: one or more objects failed to apply, reason: error when patching "/dev/shm/886469721": CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions (retried 2 times).
```
Our helm chart should disable this by default going forward.
> fix(metrics): disable CRDs deployed by grafana-agent subchart

- charts/metrics/Chart.lock
- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
Changes:
- Redo grafana-agent update to 0.41.0
- Fix breaking securityContext causing exec /bin/grafana-agent: operation not permitted (caused by addition of NET_BIND_SERVICE capability to the Dockerfile - https://github.com/grafana/agent/pull/6817/files#diff-d6958d823dc69b52225f8854987a363fb9e6d08725ab542c0d06f5443b9dee71)
Related: https://github.com/observeinc/manifests/pull/174
> fix(metrics): update grafana-agent and sync securityContext with upstream

- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/metrics/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
[Upstream GA helm chart by default (when image.tag is unset) pins the image tag to `appVersion`](https://github.com/grafana/agent/blob/6ead6f7d071f8ba9fabc0414be60c3e9b93105ef/operations/helm/charts/grafana-agent/values.yaml#L104), whereas we currently set it to `latest`. 
This results in the unexpected consequence that a user pinning to a static version of `observe/stack` or `observe/metrics` would still end up installing varying versions of grafana-agent at the image level.
With this change, we normalize to upstream chart behavior i.e., pin the image tag to appVersion.
> fix(metrics): pin grafana-agent image

- README.md
- charts/logs/Chart.yaml
- charts/logs/README.md
- charts/metrics/Chart.yaml
- charts/metrics/README.md
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/traces/Chart.yaml
- charts/traces/README.md
- charts/traces/values.yaml
`image.repository` should be set explicitly following a [breaking change](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0880-to-0890) in the upstream chart
> fix(traces): image.repository must be set

- .github/workflows/update-deps.yml
update-deps can cause version increments, which in turn can require pre-commit changes on the PR. Prior to this commit, the update-deps workflow would fail to continue on subchart updates, because pre-commit returns an exit code of `1` when it encounters diffs.
> chore(ci): workflows/update-deps precommit can continue on failure

- .github/workflows/update-deps.yml
Previously, we tried the pre-commit action which does not work, because it only checks for diffs and doesn't behave as it would locally. Since we're mainly solving for helm-docs, we prefer to use that instead.
> chore(ci): use helm-docs instead of pre-commit to auto-update chart documentation

- charts/agent/Chart.lock
- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_deployment-agent-monitor-config.tpl
- charts/agent/templates/deployment-agent-monitor-configmap.yaml
- charts/agent/values.yaml
Add pod for scraping metrics from other collector pods.  
Purpose is to separate the fate of the collectors from the collection of their health metrics so we can have reliable monitoring signals.
Other collector deployments have annotations for selection to scrape metrics
`  podAnnotations: {
observe_monitor_purpose: observecollection,
observe_monitor_scrape: 'true',
observe_monitor_path: '/metrics',
observe_monitor_port: '8888',
}`
prometheus scrape configuration only selects pods with these annotations -
observe_monitor_purpose: observecollection,
observe_monitor_scrape: 'true'
> feat: add agent monitoring pod

- charts/agent/templates/_daemonset-logs-metrics-config.tpl
- charts/agent/templates/_deployment-cluster-metrics-config.tpl
Configure k8s_cluster receiver to collect allocatable cpu, mem, storage and ephemeral-storage metrics.
Replace collected metrics k8s.{pod,node}.{cpu,mem}.utilization with their k8s.{pod,node}.{cpu,mem}.usage counterpart.
> feat: OB-35438 Collect additional k8s metrics

- charts/agent/templates/_deployment-cluster-events-config.tpl
- deployment -> deploymentName
- current/available/ready/desired/etc -> fooReplicas
- dropped deployment's total, as we should just use desired instead
- dropped ConfigMap's data, as we do NOT want to put the entire configmap data in the facets
> feat: cleanup Deployment/ReplicaSet/ConfigMap facets

- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_daemonset-logs-metrics-config.tpl
- charts/agent/templates/_deployment-agent-monitor-config.tpl
- charts/agent/templates/_deployment-cluster-events-config.tpl
- charts/agent/templates/_deployment-cluster-metrics-config.tpl
1. in k8sattributes, stop adding all labels and annotations as tags. As that is a very pretty big list with unclear value. We should enable them selectively when user needs them.
2. removed k8sattributes/podcontroller, no one is using them
3. dropped resourcedetection for all deployments This is the one that tags a lot of node level information. But, for deployments, it tags about the node that the deployment runs on, instead of the node that runs the things being monitored (e.g. pods). So, the result is very confusing. Let's just drop it. We can add selective tags back when they are useful.
4. change the debug_objectSource tag to debug_source Since it was initially used for entity/object streams only. But now it's being used for logs & metrics data too.
> feat: cleanup tagging for (mostly) metrics

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-exporters.tpl
- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_deployment-cluster-events-config.tpl
- charts/agent/templates/cluster-role.yaml
- charts/agent/templates/daemonset-logs-metrics-configmap.yaml
- charts/agent/templates/deployment-agent-monitor-configmap.yaml
- charts/agent/templates/deployment-cluster-events-configmap.yaml
- charts/agent/templates/deployment-cluster-metrics-configmap.yaml
- charts/agent/values.yaml
- Add the namespace name to cluster role and cluster role binding
- Make configmap creation conditional based on enabled flag for deployment/daemonset
- Make entity token use value drive exporter creation
Added a use field to entity token because we have to separate the creation of the secret from the usage because we deploy secrets is a separate workflow on our clusters.  Should all be temporary.
@xueweiz and I validated that this branch auto generates yaml that deploys on eng using kustomize.
Related pr - https://gerrit.observeinc.com/c/observe/+/55077
> fix: OB-35984-add-namespace-name-to-cluster-role

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_deployment-cluster-events-config.tpl
Add facets for:
- ConfigMap
- Secret
- PersistentVolume
- PersistentVolumeClaim
- Service
- Ingress
- RoleBinding
- ClusterRoleBinding
- ServiceAccount
Add name and uid for all entities (including already present ones).
These will be used by frontend to add correlation tags and enable pivoting between pages.
Remove CronJob "active" facet
This facet was computed using OTTL's Len() on a slice of pointers, which is not a supported ValueType for Len().
Therefore, this facet will have to be computed with a custom processor.
> feat: Add facets for several new resources

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-telemetry.tpl
- charts/agent/values.yaml
Allows telemetry logging to be configurable. This is currently needed for integration tests 
Eg: json as below for pod logs instead of pipe to console (default)
```
{"level":"warn","ts":1726165986.746206,"caller":"internal/resourcedetection.go:130","msg":"failed to detect resource","kind":"processor","name":"resourcedetection/cloud","pipeline":"metrics/forward","error":"isEks() error retrieving auth configmap: failed to retrieve ConfigMap kube-system/aws-auth: configmaps \"aws-auth\" not found"}
``` 
Reference: https://opentelemetry.io/docs/collector/internal-telemetry/
> feat: add option for logs encoding in telemetry

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
Add cronJobName facet to Pod events, where applies. That is, when the Pod owner's kind is "Job", and its name matches the pattern ".*\d{8}$" (ends with tac and 8 digits).
The name of the cronJob is the Job name without such substring.
> feat: add cronJobName facet to Pod

- .github/workflows/tests-integration.yaml
- integration/README.md
- integration/modules/deploy_helm/provider.tf
- integration/modules/deploy_helm/values/node_affinity.yaml
- integration/modules/deploy_helm/values/node_taint.yaml
- integration/modules/local_sandbox_kind/README.md
- integration/modules/local_sandbox_kind/main.tf
- integration/modules/local_sandbox_kind/outputs.tf
- integration/modules/local_sandbox_kind/variables.tf
- integration/modules/setup_addnl_kubernetes/main.tf
- integration/modules/setup_addnl_kubernetes/provider.tf
- integration/modules/setup_addnl_kubernetes/variables.tf
- integration/modules/setup_kind_cluster/kind.tf
- integration/pytest.ini
- integration/scripts/conftest.py
- integration/scripts/requirements.txt
- integration/scripts/test_basic.py
- integration/scripts/test_logs.py
- integration/scripts/test_nodes.py
- integration/tests/integration.tftest.hcl
- Adds matrixing of values files for parallel testing of various helm chart configurations (node_affinity, node_taint)
- Adds additional testing for configs 
We now support testing of:
- Node Taints 
- Node Affinity (toleration) 
- Namespace (not-observe) 
See: 
- https://observe.atlassian.net/browse/OB-36072
- https://github.com/observeinc/helm-charts/pull/217 (addon for this)
> ci: add integration testing for matrixing values files

- .gitignore
- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/values.yaml
- examples/agent/pod_metrics/README.md
- examples/agent/pod_metrics/pod-metrics-values.yaml
- examples/agent/pod_metrics/sample-pod-prometheus-labels-no.yaml
- examples/agent/pod_metrics/sample-pod-prometheus-labels.yaml
- Update values file to give more descriptive names and add comments for clarity
- Add new examples for prometheus labels
> feat: OB-36454 update values to new conventions and add and update tests

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
For some reason we are removing the `uid` attribute in Cluster.
Keep it, instead.
> fix: OB-37259 Keep uid alongside clusterUid for Cluster

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/templates/_config-exporters.tpl
- charts/agent/templates/_node-logs-metrics-config.tpl
- charts/agent/values.yaml
- examples/agent/logs/node-logs-values.yaml
- Default metric collection interval to 60s for all metrics collection with interval option in values file and related configs
- Added rootPath and excludeMountPoints config for host metrics
- Add comments for clarity to various section of values and template files
- Add sending metadata and write ahead log (wal) config
- Add default empty tolerations option for pods
> feat: OB-37317 add config options to cluster metrics

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
Such facets are needed to identify the CronJob that owns a Job (when the Job is not a standalone Job).
> feat: OB-36954 Add cronJobName and cronJobUid facets to Job events

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
Add "status" facet to:
- StatefulSet
- ReplicaSet
- DaemonSet
Rename "deploymentStatus" to "status" for Deployment entities.
Status is a string "Healthy"/"Unhealthy", based on the current number of replicas/pods vs desired.
> feat: Add "status" facet for various entities

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-exporters.tpl
Change from gzip (current and default) to zstd.
This change is completely transparent since our ingest can decompress zstd without issues.
> feat: Encode logs' and metrics' with zstd

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
We don't need to use the same "where" clause twice with opposite conditions. Instead, set the facet to "Healthy" and check if we need to change it to "Unhealthy"
> fix: Save ourselves an if condition in helm

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_monitor-config.tpl
- charts/agent/templates/_node-logs-metrics-config.tpl
Move observe_common attributes (k8s.cluster.name, k8s.cluster.uid) from attributes to resource_attributes for otellogs.
> fix: Move k8s.cluster.name to resource_attributes

- .gitignore
- charts/events/Chart.yaml
- charts/events/README.md
- charts/events/templates/deployment.yaml
- charts/events/values.yaml
- charts/stack/Chart.lock
- charts/stack/Chart.yaml
- charts/stack/README.md
- charts/stack/ci/test-values.yaml
Adding option to override [kube-state-events](https://github.com/observeinc/kube-state-events/tree/main) container with [include-target](https://github.com/observeinc/kube-state-events/blob/6d6b1d1e1fa39f843db75e387b1d7126a68fb132/cmd/kube-state-events/main.go#L111) and [exclude-target](https://github.com/observeinc/kube-state-events/blob/6d6b1d1e1fa39f843db75e387b1d7126a68fb132/cmd/kube-state-events/main.go#L116).
Validated with following test values:
```
containerOverrides:
excludeTargets:
- events.k8s.io/v1/events
- apps/v1/replicasets
includeTargets:
- apps/v1/deployments
```
> feat: Add overrides for excludeTargets and includeTargets

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_node-logs-metrics-config.tpl
Collect container id for both metrics and logs.
- metrics: use kubeletstats receiver's "extra_metadata_labels"
- logs: use resource processor to take the container ID from the log.file.path (attribute added by the filelog receiver)
> feat: OB-37318 Add container ID attribute

- charts/agent/templates/_cluster-events-config.tpl
Remove useless k8sattributes processor that was included by mistake
> refactor: Remove k8sattributes from k8s objects agent config

- integration/scripts/test_logs.py
Sometimes the container operator used in filelog can't recognize the file format. We ignore these errors as they are not relevant for integration tests.
> feat: Add ignore pattern in integration tests

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
Try fetching ingress class from the deprecated annotation "kubernetes.io/ingress.class", which might still contain the ingress class for outdated Ingress manifests.
> feat: Add key for fetching ingress class

- .github/workflows/tests-integration.yaml
- .gitignore
- Addresses https://observe.atlassian.net/browse/OB-37007 
Why?
- We want better reporting for terraform tests in PRs. It's currently hard to see in CI what specific test failed in which job.
- This change makes it easier to see which test failed and the error the test surfaced without scrolling through logs. 
- We use summary markdown from junit xml file to render the failure in summary screen
- We also change the naming convention for jobs to better identify things.
Other References:
Collapsing parallel github jobs (to make our CI tests less noisy in PR checks) is coming!
https://github.com/orgs/community/discussions/26246 
See example:
Scrolling....
We can see exactly what test failed, where and the output logs without having to scroll through each job logs manually. 
Another example …
> ci: add xml reporting(experimental)

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-exporters.tpl
If you use endpoint, OTel agent will append it with "/logs" as the real URL. Not what we want.
> fix: entity exporter should use logs_endpoint, instead of endpoint

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
- charts/agent/templates/_config-processors.tpl
The reason is that the custom processor might edit the log body in-place and the transform processor will copy parts of the body over to the facets. Since the transform processor is more flexible, we want to edit things first and eventually add them as facets once they are modified.
Example: secrets obfuscation. We want to redact the secrets' values that can show up in the annotations. The transform processor blindly copies the annotations to facets. So we don't want the secrets to show up in the facets un-redacted.
> fix: Swap custom and transform processors in pipeline

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-processors.tpl
We don't know how or why, but this bit of config made the associations worse, removing associations on deployments, replicasets and other stuff.
> fix: Remove problematic k8sattributes config

- examples/stack/logs/multi_line/README.md
- examples/stack/logs/multi_line/containerd-multiline.yaml
Validated on AWS EKS to combine containerd multiline.
> chore: Add example for containerd multiline CS-1457

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
The unification of events is currently defined in transform/object, which was moved after observek8sattributes due to the Secret redaction requirements.
However, the observek8sattributes custom processor expects the data from pull/watch to be unified.
The solution to this is to extract the unification logic into a different processor, which can be injected in the pipeline before observek8sattributes.
> fix: Unify pull/watch events before observek8sattributes

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/values.yaml
Files that end with *.tmp are present due to various reasons, including (but not limited to):
- Corrupted files
- Temporary files written while performing log rotation
These files contain binary data, which we cannot parse as logs anyways These files also cause errors when processed by the receiver, since filelog cannot recognize the log format due to their binary encoding.
> fix: Do not read logs from tmp files

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-processors.tpl
fix: change the action from insert to upsert to properly override k8s.cluster.name for GKE.
> fix: change the action from insert to upsert

- integration/scripts/conftest.py
- integration/scripts/test_logs.py
Addresses https://observe.atlassian.net/browse/OB-38641
`test_logs.py` has been updated to parse logs as JSON (they are set as JSON in debug) and extract `level: <>` information for checks
> ci: update test logs for json error parsing

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config.tpl
- charts/agent/templates/agent-monitor-configmap.yaml
- charts/agent/templates/cluster-events-configmap.yaml
- charts/agent/templates/cluster-metrics-configmap.yaml
- charts/agent/templates/node-logs-metrics-configmap.yaml
- charts/agent/values.yaml
- examples/agent/additionalOTELConfiguration/README.md
- examples/agent/additionalOTELConfiguration/additional-otel-config-values.yaml
This change allows for additional OTEL Config to be provided for each of the 4 deployments of the Observe Agent in the Helm chart. The custom config will be take precedence and will be merged with the config generated from the chart templates for each of the services.
> feat: allow custom otel config to be injected to services

- examples/stack/logs/multi_line/README.md
- examples/stack/logs/multi_line/multiline-containerd-timestamps-values.yaml
- examples/stack/logs/multi_line/multiline-containerd-values.yaml
- examples/stack/logs/multi_line/multiline-java-values.yaml
Added example using the default Java parser.
Added example matching timestamps with any of the following timestamps: 2024-12-03 07:31:12,563
07:31:20,550
[2024-12-03 07:31:28.353]
> chore: Add example for containerd multiline timestamp and java CS-1402

- examples/stack/logs/multi_line/multiline-containerd-timestamps-values.yaml
Update LUA and multiline to handle `stdout F` and `stdout P`
> fix: Update LUA and multiline

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-exporters.tpl
In order for the out of box routing to work, send all traces to shared "Tracing" package and all other data to host connection specific "Kubernetes Explorer".
In the future those will be configurable.
> feat: add default routing headers

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_node-logs-metrics-config.tpl
- charts/agent/values.yaml
This PR addresses an issue where the `kubeletstats` receiver in the agent fails to scrape metrics, resulting in a `connection refused` error. The failure occurs because the current configuration uses the node's hostname (via `K8S_NODE_NAME`), which resolves to the loopback address (`127.0.1.1`) instead of the node's actual IP. This prevents the receiver from reaching the kubelet’s `/stats/summary` endpoint on port 10250.
Added an override in for `node.kubeletstats.useNodeIp: true` to update the endpoint to use `K8S_NODE_IP` if set or default to `K8S_NODE_NAME`.
> fix: Replace kubeletstats to use node IP address - (OBSSD-482)

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-processors.tpl
GOMEMLIMIT gets automatically set to 80% of the Kube resources so this should be 80% total as well
> fix: lower memory-limiter to 80

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/templates/_config-processors.tpl
`k8s_container_restarts` / `k8s.container.restarts` and similar metrics are broken when container.id is part of the labels. In general, it's largely just adding extra dimensionality without much benefit. Hence remove completely from cluster metrics.
Fixes OB-44943
> fix: Remove container id for cluster metrics

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-metrics-config.tpl
- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_monitor-config.tpl
- charts/agent/templates/_prometheus-scraper-config.tpl
Currently the prometheus receiver is setting the prom scrape job name as `service.name`:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.128.0/receiver/prometheusreceiver/internal/prom_to_otlp.go#L53
We need to delete this so `service.name` is set properly by `k8sattributes` processor.
> fix: populate service.name correctly on scraped prometheus metrics

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/ci/test-values.yaml
- charts/agent/templates/_forwarder-config.tpl
- charts/agent/values.yaml
- integration/scripts/benchmark/log_generator.py
- integration/scripts/benchmark/metrics_generator.py
- integration/scripts/benchmark/trace_generator.py
- integration/scripts/test_benchmark.py
This adds an option to generate RED metrics from spans in the agent forwarder. These will be used to power our Service Explorer and eventually allow standardized trace sampling.
I ran the benchmarking test with the medium volume trace data and low for everything else. The quick results show about a ~10% difference in CPU usage and <2% increase in RAM usage.
> feat: add option to enable RED metrics generation from spans

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/prometheus-scraper-configmap.yaml
I think this was a copy paste error.
> fix: only create prometheus scraper configmap when the deployment is enabled

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/values.yaml
I ran this locally with the following values file:
```yaml
node:
enabled: false
forwarder:
enabled: true
forwarder:
mode: deployment
replicaCount: 2
```
I used `helm template` to diff the generated k8s files, and (with a bit of reordering to help `diff` out), the result is:
```diff
diff --git a/helm/export.yaml b/helm/export.yaml
index bb2a508..a52bf6d 100644
--- a/helm/export.yaml
+++ b/helm/export.yaml
@@ -87,13 +87,13 @@ metadata:
app.kubernetes.io/instance: observe-agent
app.kubernetes.io/version: "0.126.0"
app.kubernetes.io/managed-by: Helm
-    app.kubernetes.io/component: agent-collector
+    app.kubernetes.io/component: standalone-collector
spec:
podSelector:
matchLabels:
app.kubernetes.io/name: forwarder
app.kubernetes.io/instance: observe-agent
-      component: agent-collector …
```
> feat: add comments to values.yaml detailing how to install the chart in a serverless k8s environment

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_config-pipelines.tpl
- charts/agent/templates/_config-processors.tpl
- charts/agent/templates/_forwarder-config.tpl
Using empty string instead of null greatly simplifies the OPAL handling.
Agent PR: https://github.com/observeinc/observe-agent/pull/239
> fix: handle null service resource attributes in RED metrics

- charts/agent/Chart.yaml
- charts/agent/README.md
- charts/agent/templates/_cluster-events-config.tpl
We currently set the status of various workload objects to "Unhealthy" when readyReplicas != desiredReplicas. However, sometimes readyReplicas could be omitted (instead of being set to 0) if no replicas are ready.
At the same time, in particular cases, one could set desiredReplicas to 0 (for whatever reason).
In this case, with the current logic, the object would always be considered "Unhealthy" since nil != 0.
Treat nil as 0 to consider objects defined with desiredReplicas == 0 always "Healthy".
> fix: Treat "nil" ready replicas as 0
