observeinc/helm-charts

README.md
examples/stack/values-l.yaml
examples/stack/values-m.yaml
examples/stack/values-xl.yaml
examples/stack/values-xs.yaml
examples/traces/values-deployment.yaml
examples/traces/values-m.yaml
examples/traces/values-xs.yaml

This change adds more information on namespaces, example sizes, storing values files, and advanced subchart config overrides. It also also updates the example size values files to complete chart configurations to avoid user error.

docs: README improvements

---

examples/traces/values-config.yaml
examples/traces/values-memlimit.yaml

Adds an example around overriding OTEL collector configuration

add otel configuration examples

---

.github/workflows/pre-commit.yml
Makefile
bump_version.sh

- add a bash script / Make task to update Chart.yaml ( [example](https://github.com/hutchic-observe-meta/helm-charts/pull/1/commits/e35599127102f5a1926837c4d24c303af038196c) )
- add a github actions to spot check that Chart.yaml is updated appropriately ( [example](https://github.com/hutchic-observe-meta/helm-charts/actions/runs/6224892802/job/16894112642) )

chore(ci): validate Chart.yaml is updated when necessary

---

charts/stack/Chart.lock
charts/stack/Chart.yaml
charts/stack/README.md
charts/traces/Chart.yaml
charts/traces/README.md
charts/traces/values.yaml

Enable collection and ingestion of OpenTelemetry logs
Equivalent Manifest PR: https://github.com/observeinc/manifests/pull/120

feat(traces): collect and ingest open-telemetry logs

---

.github/workflows/pre-commit.yml
.github/workflows/update-deps.yml
Makefile
updatecli/external/fluent-bit.yml
updatecli/external/grafana.yml
updatecli/external/open-telemetry.yml
updatecli/internal/01_endpoint.yml
updatecli/internal/02_proxy.yml
updatecli/internal/03_events.yml
updatecli/internal/03_logs.yml
updatecli/internal/03_metrics.yml
updatecli/internal/03_traces.yml
updatecli/internal/04_stack.yml

Generates update PR's
Validates PR's have updated all the necessary Chart.yaml version bumps

chore: setup updatecli and a gha job

---

charts/events/Chart.yaml
charts/events/README.md
charts/events/templates/deployment.yaml
charts/events/values.yaml
charts/logs/Chart.yaml
charts/logs/README.md
charts/stack/Chart.lock
charts/stack/Chart.yaml
charts/stack/README.md
charts/traces/Chart.yaml
charts/traces/README.md

https://observe.atlassian.net/browse/CS-236

feat: add node affinity to events values

---

charts/metrics/Chart.yaml
charts/metrics/README.md
charts/metrics/values.yaml
charts/stack/Chart.lock
charts/stack/Chart.yaml
charts/stack/README.md

Address #3 (https://observe.atlassian.net/browse/OB-27594?filter=10366) 
Tested in environment:

fix(metrics): drop container_fs metrics

---

charts/logs/Chart.lock
charts/logs/Chart.yaml
charts/logs/README.md
charts/stack/Chart.lock
charts/stack/Chart.yaml
charts/stack/README.md

Updated fluent-bit version update to 0.46.7

fix(fluent-bit): fluent-bit version update to resolve CVE-2024-4323

---

charts/agent/Chart.lock
charts/agent/README.md
charts/agent/templates/_config-exporters.tpl
charts/agent/templates/_config-processors.tpl
charts/agent/templates/_daemonset-logs-metrics-config.tpl
charts/agent/templates/_deployment-cluster-events-config.tpl
charts/agent/templates/_deployment-cluster-metrics-config.tpl
charts/agent/templates/_observe-agent.tpl
charts/agent/templates/cluster-role.yaml
charts/agent/values.yaml

1. fixed pod controller facets
2. enabled hostfs and kubeletstats metric collection properly
3. enabled k8sattributes properly for the kubeletstats metrics
(#2 and #3 was broken because the presets were dropped during the repo migration.

fix: Overhaul on daemonset and events deployment

---

charts/agent/Chart.lock
charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_config-exporters.tpl
charts/agent/templates/_daemonset-logs-metrics-config.tpl
charts/agent/templates/_deployment-cluster-events-config.tpl
charts/agent/templates/_deployment-cluster-metrics-config.tpl
charts/agent/values.yaml

1. Add exporter and conditional pipeline section for entity endpoint base on entityToken presence
2. Change ottlp/http to base exporter
3. Add trim for endpoint that handles trailing slash or not

fix: ob-35088 add entity endpoint for objects

---

charts/agent/templates/_deployment-cluster-events-config.tpl

This reverts commit 8e5b1898b3f2ac6dd699ff8393e291dfaec8b663.

fix: Revert "feat: add podCIDR facet for Node"

---

charts/agent/Chart.lock
charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_config-exporters.tpl
charts/agent/templates/_deployment-cluster-events-config.tpl
charts/agent/templates/secret.yaml
charts/agent/values.yaml

Creates a template for secret creation on cluster to hold observe token

feat: ob35943 create secret for token

---

charts/agent/templates/_deployment-cluster-events-config.tpl
charts/agent/values.yaml

Add a variety of facets for the following new entities:
- Job
- CronJob
- StatefulSet
- DaemonSet

feat: Add Workload entities with straightforward facets

---

charts/agent/Chart.lock
charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_config-exporters.tpl
charts/agent/templates/_config-processors.tpl
charts/agent/templates/_config-telemetry.tpl
charts/agent/templates/_helpers.tpl
charts/agent/values.yaml

- add conditions to chart.yaml and values.yaml to provide override for each deployment

feat: OB-35984 add conditional enabled values for each deployment

---

charts/agent/Chart.lock
charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_config-exporters.tpl
charts/agent/templates/_deployment-cluster-events-config.tpl
charts/agent/templates/secret.yaml
charts/agent/values.yaml

- Made TOKEN and ENTITY_TOKEN environment variables optional and adjusted template files to accomodate

feat: OB-35984 add optional env vars for tokens

---

charts/agent/Chart.lock
charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/values.yaml

- Enabled flags have been moved to top of values file

fix: Remove unused yaml properties

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_deployment-cluster-events-config.tpl

E.g. replicasetName --> replicaSetName

fix: Capitalize facets named after two-word entities

---

examples/stack/logs/README.md
examples/stack/logs/custom-values.yaml

- Shows how to add labels and annotations to logs (fluent-bit) pod
- Shows how to use kubernets filter to add labels and annotations to pod logs

feat: CS-1087 add logs chart modification example

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_observe-agent.tpl

- Updates`token: {{ .Values.observe.token.value }} `  for correct naming

fix: update observe-agent.tpl

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/values.yaml
examples/agent/affinity/README.md
examples/agent/affinity/affinity-values.yaml
examples/agent/affinity/node-affinity-daemonset.yaml
examples/agent/affinity/taint-values.yaml

OB-36455
OB-35951
- Adds examples for using affinity and taints
- Adds default anti-affinity rules to values file

feat: OB-35951 add affinity and taint examples

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl

Nested objects are harder to handle, let's avoid that, and focus on the most useful information here.

feat: simplify Event's identifiers field

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl

Add capacity facet to PersistentVolume
Rename other facets that had "persistentVolume" in the key name. Remove that

feat: add PersistentVolume capacity

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-metrics-config.tpl
charts/agent/templates/_monitor-config.tpl
charts/agent/values.yaml
examples/agent/affinity/affinity-values.yaml
examples/agent/pod_metrics/README.md
examples/agent/pod_metrics/pod-metrics-values.yaml
examples/agent/pod_metrics/sample-pod-no.yaml
examples/agent/pod_metrics/sample-pod.yaml

- Add configuration for pod metrics to: 
- values.yaml 
- _cluster-metrics-config.tpl
- Add example for pod metrics to helm-charts/examples/agent/pod_metrics

feat: OB-36454 add pod metrics config

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl

Add such attributes to resource attributes also for cluster object (currently only for other objects)

fix: Add clusterName and clusterUid to resource attributes

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl
charts/agent/templates/_config-processors.tpl

Possible values "Healthy" or "Unhealthy", based on the number of ready replicas vs desired

feat: OB-37620 Add deployment status facet

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/values.yaml

- Based on log rotation patterns current files may not be completely read

fix: missing glob pattern for log rotation

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl

Allows for easier debugging of facets

feat: Add agent version to control fields

---

.gitignore
examples/agent/logs/log-generator.sh
examples/agent/logs/sample-log-pods.yaml
examples/stack/logs/multi_line/README.md
examples/stack/logs/multi_line/multiline-values.yaml

Adds example for logs chart to get multiline logs

chore: Add example for multiline

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/templates/_cluster-events-config.tpl
charts/agent/templates/_config-exporters.tpl
charts/agent/values.yaml
integration/modules/deploy_helm/values/default.yaml
integration/modules/deploy_helm/values/node_affinity.yaml
integration/modules/deploy_helm/values/node_taint.yaml

Send everything to the /v1/kubernetes/v1/entity path

feat: Cleanup values.yaml with sensible defaults

---

charts/events/Chart.yaml
charts/events/README.md
charts/events/templates/deployment.yaml
charts/stack/Chart.lock
charts/stack/Chart.yaml
charts/stack/README.md
charts/stack/ci/test-values.yaml

Support adding `values.customLabels` to pods

feat(events): apply customLabels to pods

---

integration/scripts/test_logs.py

- Minor bug fix to address `level:error` error is show in `error: <>` instead of `msg: <>`

ci: update test log for error

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/values.yaml

Observe Agent v1.6.0 Changelog: https://github.com/observeinc/observe-agent/releases/tag/v1.6.0

feat: bump observe-agent image version to 1.6.0

---

examples/stack/logs/multi_line/README.md
examples/stack/logs/multi_line/multiline-containerd-combine-java-stacktrace.yaml

Added a multiline example to combine logs that begin with `[INFO]` OR `[WARN]` OR `[ERROR]`

feat: Update multiline examples

---

examples/agent/logs/multiline/README.md
examples/agent/logs/multiline/recombine_multiline_example.yaml
examples/agent/logs/sample_logs/log-generator.sh
examples/agent/logs/sample_logs/sample-log-pods.yaml

CS-1844
add multiline examples

feat(multiline): add multiline examples

---

charts/agent/Chart.yaml
charts/agent/README.md
charts/agent/values.yaml

This is inline with the usage we observed in our 10k DPS high volume scenario.
Related to: https://github.com/observeinc/helm-charts/pull/327

fix: tune default resource values after benchmark testing

---

.github/workflows/orca.yaml

- Add Orca  SAST, SCA & IaC Scan Workflow for helm-charts repo

chore: add orca

---

charts/agent/templates/_config-connectors.tpl
charts/agent/templates/_config-pipelines.tpl
charts/agent/templates/_config-processors.tpl
charts/agent/templates/_config.tpl
charts/agent/templates/_forwarder-config.tpl

This is all code motion to help simplify the Gateway deployment diff

refactor: move RED metrics specific config to helper files
